### ISSUE TITLE
can you add demo project to use this ?? i want to detect gender of speaker for my collage project.

### ISSUE THREAD

**Issue by cloudjanak** [stephencelis/sc_listener#4]

**Comment by stephencelis** [comment]
Please see the note at the top of the project's README!

**Comment by cloudjanak** [comment]
if i want to use this,please provide demo project

**Comment by stephencelis** [comment]
Again, please look at the README. This project is basically defunct. I wouldn't recommend using this and won't be updating it or providing a demo.
